version: '3.5'

services:
  proxy:
    image: proxy-network
    container_name: proxy-network
    privileged: true
    environment:
      TZ: 'Asia/Tokyo'
      DHPARAM_GENERATION: false
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost.d:/etc/nginx/vhost.d
    networks:
      - proxy-network
    logging:
      driver: 'json-file'
      options:
        max-size: '3m'
        max-file: '1'

networks:
  proxy-network:
    name: proxy-network
